//this is navbar buttons
var buttons = [
  { title: "Bedding", backgroundColor: "white" },
  { title: "Kitchen & Dining", backgroundColor: "white" },
  { title: "Home Decor", backgroundColor: "white" },
  { title: "Home Essentials", backgroundColor: "white" },
  { title: "Stroage & Organization", backgroundColor: "white" },
  { title: "lighting and lamp", backgroundColor: "white" },
  { title: "Bathroom", backgroundColor: white },
  { title: "Event party Supplies", backgroundColor: "white" },
  { title: "Pet Supplies", backgroundColor: "white" },
  { title: "SHIEN BASIC LIVING", backgroundColor: "white" },
  { title: "Home Improvement", backgroundColor: "white" },
  { title: "Holiday", backgroundColor: "white" },
];

//this is category data//
var categories = [
  {
    category: "bedding",
    subcategory: "bedding",
    title: "1 pair Christmas print Pillowcase",
    price: "US$10.00",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingImages/img2.webp",
      "/home/sumit/Desktop/sheinProject/beddingImages/img2.1.webp",
      "/home/sumit/Desktop/sheinProject/beddingImages/img2.2.webp",
      "/home/sumit/Desktop/sheinProject/beddingImages/img2.4.webp",
    ],
  },
  {
    category: "bedding",
    subcategory: "bedding",
    title: "1pc plain Plush Blanket",
    price: "US$54.00",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    imgUrl: ["/home/sumit/Desktop/sheinProject/beddingImages/img1.webp"],
  },
  {
    category: "bedding",
    subcategory: "bedding",
    title: "1pair Fleece Pillowcase Without Filler",
    price: "US$14.00",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    imgUrl: ["/home/sumit/Desktop/sheinProject/beddingImages/img4.webp"],
  },
  {
    category: "bedding",
    subcategory: "bedding",
    title: "Butterfly Print Duvet Coever Set Without",
    price: "US$37.00",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/img5.webp",
      "/home/sumit/Desktop/sheinProject/beddingImages/img5.1.webp",
      "/home/sumit/Desktop/sheinProject/beddingImages/img5.2.webp",
    ],
  },
  {
    category: "bedding",
    subcategory: "bedding",
    title: "1pair Fleece Pillowcase Without Filler",
    price: "US$15.00",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    imgUrl: ["/home/sumit/Desktop/sheinProject/beddingImages/img3.webp", "/home/sumit/Desktop/sheinProject/beddingImages/img3.1.webp"],
  },
  {
    category: "bedding",
    SubCategory: "bedSkirt",
    title: "Pom Pom Bed Skirt",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$19.00",
    imgUrl: ["/home/sumit/Desktop/sheinProject/beddingCategory/img1.webp", "/home/sumit/Desktop/sheinProject/beddingCategory/img1.1.webp"],
  },
  {
    category: "bedding",
    SubCategory: "bedSkirt",
    title: "Plain Ruffle Bed Skirt",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$24.00",
    imgUrl: ["/home/sumit/Desktop/sheinProject/beddingCategory/img2.webp"],
  },
  {
    category: "bedding",
    SubCategory: "bedSkirt",
    title: "Flower Print Bed Skirt",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$19.00",
    imgUrl: ["/home/sumit/Desktop/sheinProject/beddingCategory/img3.webp"],
  },
  {
    category: "bedding",
    SubCategory: "bedSkirt",
    title: "Houndstooth pattern Bed Skirt",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$35.00",
    imgUrl: ["/home/sumit/Desktop/sheinProject/beddingCategory/img4.webp"],
  },
  {
    category: "bedding",
    SubCategory: "bedSkirt",
    title: "Plain Print Bed Skirt",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$35.00",
    imgUrl: ["/home/sumit/Desktop/sheinProject/beddingCategory/img5.webp"],
  },
  {
    category: "bedding",
    SubCategory: "bedSpread",
    title: "Gradient color Spreadsheet",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$41.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/bedspreadandRunners/gradientColor.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/bedspreadandRunners/gradientColorSmall.webp",
    ],
  },
  {
    category: "bedding",
    SubCategory: "bedSpread",
    title: "Pizaa print spreadheet",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$28.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/bedspreadandRunners/pizaaPrint.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/bedspreadandRunners/pizzaPrintSmall.webp",
    ],
  },
  {
    category: "bedding",
    SubCategory: "bedSpread",
    title: "Star Print spreadsheet",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$33.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/bedspreadandRunners/starPrint.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/bedspreadandRunners/starPrintSmall.webp",
    ],
  },
  {
    category: "bedding",
    SubCategory: "bedSpread",
    title: "christmas pattern spreasheet",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$40.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/bedspreadandRunners/christmasPattern.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/bedspreadandRunners/christmasPatternSmall.webp",
    ],
  },
  {
    category: "bedding",
    SubCategory: "blankets",
    title: "christmas print blanket",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$28.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/blankets/christmasPrint.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/blankets/christmasPrintSmall.webp",
    ],
  },
  {
    category: "bedding",
    SubCategory: "blankets",
    title: "christmas Santa print blanket",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$32.99",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/blankets/christmasSanta.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/blankets/christmasSantaSmall.webp",
    ],
  },
  {
    category: "bedding",
    SubCategory: "blankets",
    title: "halloween Spider print",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$42.23",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/blankets/halloweenSpider.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/blankets/halloweenSpiderSmall.webp",
    ],
  },
  {
    category: "bedding",
    SubCategory: "blankets",
    title: "christmas deer print blanket",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$72.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/blankets/christmas Deer blanket small.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/blankets/Christmas Deer blanket.webp",
    ],
  },
  {
    category: "bedding",
    subcategory: "sheetsAndPillow",
    title: "1 pair pillows Santa printed",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$19.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/sheetsAndPillowcase/1pairpillowSanta.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/sheetsAndPillowcase/1pairpillowSantaSmall.webp",
    ],
  },
  {
    category: "bedding",
    subcategory: "sheetsAndPillow",
    title: "Christmasn print sheet",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    size: ["one-size", "s", "m", "xl", "l"],
    price: "US$27.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/sheetsAndPillowcase/chistmasPrintedSheet.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/blankets/christmasPrintedSmall.webp",
    ],
  },
  {
    category: "bedding",
    subcategory: "sheetsAndPillow",
    title: "Christmas print Deer",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    price: "US$21.00",
    size: ["one-size", "s", "m", "xl", "l"],
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/sheetsAndPillowcase/christmasPrintDeer.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/sheetsAndPillowcase/christmasPrintDeerSmall.webp",
    ],
  },
  {
    category: "bedding",
    subcategory: "sheetsAndPillow",
    title: "Tree print sheet",
    color: ["red", "green", "blue", "yellow", "black", "grey"],
    price: "US$38.00",
    size: ["one-size", "s", "m", "xl", "l"],
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/beddingCategory/sheetsAndPillowcase/TreePrintSheet.webp",
      "/home/sumit/Desktop/sheinProject/beddingCategory/sheetsAndPillowcase/TreePrintSheetSmall.webp",
    ],
  },
  //this is dining and dinner category//
  {
    category: "diningKitchen",
    subcategory: "Kichen",
    title: "100pc Elk spoon chirstmas",
    color: "gold",
    size: "one-size",
    price: "US$4.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/100pcChristmasElkSpoon.webp",
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/100pcChristmasElkSpoonSmall.webp",
    ],
  },
  {
    category: "diningKitchen",
    subcategory: "Kichen",
    title: "christmas pattern placemat",
    color: "gold",
    size: "one-size",
    price: "US$5.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/christamasPlacematPattern.webp",
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/christmasPatternPlacematSmall.webp",
    ],
  },
  {
    category: "diningKitchen",
    subcategory: "Kichen",
    title: "christmas slogan dinner",
    color: "red",
    size: "one-size",
    price: "US$3.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/christmasSlogan.webp",
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/christmasSloganSmall.webp",
    ],
  },
  {
    category: "diningKitchen",
    subcategory: "Kichen",
    title: "christmas wine Glass set",
    color: "white",
    size: "one-size",
    price: "US$8.00",
    imgUrl: [
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/christmasWineGlass.webp",
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/christmasWineGlassSmalll.webp",
    ],
  },
  {
    category: "diningKitchen",
    subcategory: "Kichen",
    title: "christmas elk print ",
    color: "black",
    size: "one-size",
    price: "US$12.00",
    imgUrl: [
      "sheinProject/diningkitchen/kitchen/christmasElkPrint.webp",
      "sheinProject/diningkitchen/kitchen/christmasElkPrintSmall.webp",
    ],
  },

  {
    category: "diningKitchen",
    subcategory: "Kitchen",
    title: "1pc random floral arpon",
    color:"random",
    size:["S","M","L","XL"],
    price: "US$8.00",
    imgUrl : [
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/1pc radnom floral apron.webp",
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/1pc random floral apron small.webp",
    ],
  },

  {
    category: "diningKitchen",
    subcategory: "Kitchen",
    title: "1pc random color lunchbox",
    color:"random",
    size:["one-size"],
    price: "US$12.00",
    imgUrl : [
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/1pc random color lunchbox .webp",
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/1pc random color lunchbox small.webp",
    ],
    
  },
  {
    category: "diningKitchen",
    subcategory: "Kitchen",
    title: "1pc stainless steel garlic press",
    color:"silver",
    size:["one-size"],
    price: "US$4.00",
    imgUrl : [
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/1pc stainless steel garlic press small.webp",
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/1pc stainless steel garlic press.webp",
    ],
  },
  {
    category: "diningKitchen",
    subcategory: "Kitchen",
    title: "4pc stainless steel spoon",
    color:"silver",
    size:["one-size"],
    price: "US$3.00",
    imgUrl : [
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/4pc stainless steel spoon small.webp",
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/4pc stainless steel spoon.webp",
    ],
  },
  {
    category: "diningKitchen",
    subcategory: "Kitchen",
    title: "1pc gradient water bottle ",
    color:"gradient",
    size:["1000ml"],
    price: "US$21.00",
    imgUrl : [
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/1pc gradient water bottle.webp",
      "/home/sumit/Desktop/sheinProject/diningkitchen/kitchen/1pc gradient water  bottle small.webp",
    ],
  },

<<<<<<< Updated upstream
  
=======
  //home decor
  {
    category: "homedecor",
    subcategory: "home",
    title: "1pc marble print wallpaper",
    size: "one-size",
    color: "red",
    price : "US$21.00",
    imgUrl : ["marble print wallpaper small.webp","marble print wallpaper.webp"],
    
  },
 
  {
    category: "homedecor",
    subcategory: "home",
    title: "moon shaped tassesl home decor",
    size: "one-size",
    color: "silver",
    price : "US$24.00",
    imgUrl : ["/home/sumit/Desktop/sheinProject/homeDecor/moon shaped tassel home decor  small.webp","moon shaped tassel home decor.webp"],
         
  },
  {
    category: "homedecor",
    subcategory: "home",
    title: "plain plush home decor",
    size: "one-size",
    color: "silver",
    price : "US$18.00",
    imgUrl : ["/home/sumit/Desktop/sheinProject/homeDecor/plain plush home decor small.webp","/home/sumit/Desktop/sheinProject/homeDecor/plain plush home decor small.webp"],
         
  },
  {
    category: "homedecor",
    subcategory: "home",
    title: "slogan printed cushion cover",
    size: "one-size",
    color: "white",
    price : "US$12.00",
    imgUrl : ["/home/sumit/Desktop/sheinProject/homeDecor/slogan printed cushion cover small.webp","/home/sumit/Desktop/sheinProject/homeDecor/slogan printed cushion cover.webp"],
   
  },
  {
    category: "homedecor",
    subcategory: "home",
    title: "slogan printed mirror",
    size: "one-size",
    color: "random",
    price : "US$19.00",
    imgUrl : ["/home/sumit/Desktop/sheinProject/homeDecor/slogan printed mirror small.webp","/home/sumit/Desktop/sheinProject/homeDecor/slogan printed mirror.webp"],
   
  },
  {
    category: "homedecor",
    subcategory: "home",
    title: "sun printed tapestry",
    size: "one-size",
    color: "random",
    price : "US$22.00",
    imgUrl : ["/home/sumit/Desktop/sheinProject/homeDecor/sun print tapestry.webp","/home/sumit/Desktop/sheinProject/homeDecor/sun print tapestry small.webp"],
   
  },
  {
    category: "homedecor",
    subcategory: "home",
    title: "toilet entrance sticker ",
    size: "one-size",
    color: "random",
    price : "US$18.00",
    imgUrl : ["/home/sumit/Desktop/sheinProject/homeDecor/toilet entrance sticker.webp","/home/sumit/Desktop/sheinProject/homeDecor/toilet entrance sticker small.webp"],
   
  },

  //if image are not showing remove home/suumit/desktop from the image path
>>>>>>> Stashed changes
];

localStorage.setItem("categoryProducts", JSON.stringify(categories));

var buttons = [
  { title: "Bedding", backgroundColor: "white" },
  { title: "Kitchen & Dining", backgroundColor: "white" },
  { title: "Home Decor", backgroundColor: "white" },
  { title: "Home Essentials", backgroundColor: "white" },
  { title: "Stroage & Organization", backgroundColor: "white" },
  { title: "lighting and lamp", backgroundColor: "white" },
  { title: "Bathroom", backgroundColor: white },
  { title: "Event party Supplies", backgroundColor: "white" },
  { title: "Pet Supplies", backgroundColor: "white" },
  { title: "SHIEN BASIC LIVING", backgroundColor: "white" },
  { title: "Home Improvement", backgroundColor: "white" },
  { title: "Holiday", backgroundColor: "white" },
];
